// API BASIC TYPES
export const PREFIX = "@@_api_";
export const REQUEST = "_REQUEST";
export const LOADING = "_LOADING"; //
export const SUCCESS = "_SUCCESS";
export const POST_SUCCESS = "_POST_SUCCESS";
export const ERROR = "_ERROR";
export const CLOSE = "_CLOSE";

// LOCATION
export const LOCATION_BASE = PREFIX + "LOCATION";
export const LOCATION_REQUEST = LOCATION_BASE + REQUEST;
export const LOCATION_LOADING = LOCATION_BASE + LOADING;
export const LOCATION_SUCCESS = LOCATION_BASE + SUCCESS;
export const LOCATION_POST_SUCCESS = LOCATION_BASE + POST_SUCCESS;
export const LOCATION_ERROR = LOCATION_BASE + ERROR;
export const LOCATION_CLOSE = LOCATION_BASE + CLOSE;

// FORECAST
export const FORECAST_BASE = PREFIX + "FORECAST";
export const FORECAST_REQUEST = FORECAST_BASE + REQUEST;
export const FORECAST_LOADING = FORECAST_BASE + LOADING;
export const FORECAST_SUCCESS = FORECAST_BASE + SUCCESS;
export const FORECAST_POST_SUCCESS = FORECAST_BASE + POST_SUCCESS;
export const FORECAST_ERROR = FORECAST_BASE + ERROR;
export const FORECAST_CLOSE = FORECAST_BASE + CLOSE;
